[package]
name = "lekiwi-zenoh-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = "1.49.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
zenoh = "1.7.2"
